import esbuild from "esbuild";
import fs from 'fs';
import process from "process";
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';
import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

// Ensure build folder exists
if (!fs.existsSync('build')) {
    fs.mkdirSync('build');
}

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ['main.ts'],
    bundle: true,
    minifyWhitespace: true,
    minifyIdentifiers: true,
    minifySyntax: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
    ],
    format: 'cjs',
    target: 'es2018',
    logLevel: "info",
    //sourcemap: prod ? false : 'inline',
    sourcemap: false,
    treeShaking: true,
    outfile: 'build/lua-console/main.js',
    platform: 'browser',
    plugins: [
        NodeGlobalsPolyfillPlugin({
            process: true,
            buffer: true,
        }),
        NodeModulesPolyfillPlugin()
    ],
    define: {
        'global': 'window',
        'process.env.NODE_ENV': '"production"'
    }
});

await context.rebuild();
process.exit(0);